package it.water.connectors.hbase.api;

import it.water.core.api.service.BaseApi;

import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods for HBase integration.
 */
public interface HBaseConnectorApi extends BaseApi {

    void checkConnection() throws IOException;

    void createTable(String tableName, List<String> columnFamilies) throws IOException;

    void deleteData(String tableName, String rowKey) throws IOException;

    void disableTable(String tableName) throws IOException;

    void dropTable(String tableName) throws IOException;

    void enableTable(String tableName) throws IOException;

    void insertData(String tableName, String rowKey, String columnFamily, String column, String cellValue)
        throws IOException;

    Map<byte[], Map<byte[], Map<byte[], byte[]>>> scan(
        String tableName,
        Map<byte[], List<byte[]>> columns,
        byte[] rowKeyLowerBound,
        byte[] rowKeyUpperBound,
        int limit
    ) throws IOException;
}
