package it.water.connectors.hbase.api;

import it.water.core.api.service.BaseSystemApi;

import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * @Generated by Water Generator
 * Internal API for HBaseConnector; bypasses permission checks.
 */
public interface HBaseConnectorSystemApi extends BaseSystemApi {

    void executeTask(Runnable runnableTask);

    void checkConnection() throws IOException;

    void createTable(String tableName, List<String> columnFamilies) throws IOException;

    void createTableAsync(String tableName, List<String> columnFamilies) throws IOException;

    void deleteData(String tableName, String rowKey) throws IOException;

    void deleteDataAsync(String tableName, String rowKey);

    void disableTable(String tableName) throws IOException;

    void disableTableAsync(String tableName);

    void disableAndDropTable(String tableName) throws IOException;

    void disableAndDropTableAsync(String tableName);

    void dropTable(String tableName) throws IOException;

    void dropTableAsync(String tableName);

    void enableTable(String tableName) throws IOException;

    void insertData(String tableName, String rowKey, String columnFamily, String column, String cellValue)
        throws IOException;

    void insertDataAsync(String tableName, String rowKey, String columnFamily, String column, String cellValue);

    long rowCount(String tableName, byte[] columnFamily, byte[] column, byte[] rowKeyLowerBound, byte[] rowKeyUpperBound)
        throws Throwable;

    long rowCount(String tableName, Map<byte[], List<byte[]>> columns, byte[] rowKeyLowerBound, byte[] rowKeyUpperBound)
        throws Throwable;

    List<byte[]> scan(
        String tableName,
        byte[] columnFamily,
        byte[] column,
        byte[] rowKeyLowerBound,
        byte[] rowKeyUpperBound
    ) throws IOException;

    Map<byte[], Map<byte[], Map<byte[], byte[]>>> scan(
        String tableName,
        Map<byte[], List<byte[]>> columns,
        byte[] rowKeyLowerBound,
        byte[] rowKeyUpperBound,
        int limit
    ) throws IOException;

    boolean tableExists(String tableName) throws IOException;
}
