package it.water.connectors.hbase.api;

import it.water.core.api.repository.BaseRepository;
import it.water.core.interceptors.annotations.*;
import it.water.connectors.hbase.model.HBaseConnector;

/**
 * @Generated by Water Generator
 * Interface component for HBaseConnector Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 *
 */
public interface HBaseConnectorRepository extends BaseRepository<HBaseConnector> {
	
}
