package it.water.connectors.hbase.service;

import it.water.connectors.hbase.api.HBaseConnectorApi;
import it.water.connectors.hbase.api.HBaseConnectorSystemApi;
import it.water.connectors.hbase.model.HBaseConnector;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.repository.service.BaseEntityServiceImpl;
import lombok.Getter;
import lombok.Setter;

import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * @Generated by Water Generator
 * Service API class for HBaseConnector entity.
 */
@FrameworkComponent
public class HBaseConnectorServiceImpl extends BaseEntityServiceImpl<HBaseConnector> implements HBaseConnectorApi {

    @Inject
    @Getter
    @Setter
    private HBaseConnectorSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public HBaseConnectorServiceImpl() {
        super(HBaseConnector.class);
    }

    @Override
    public void checkConnection() throws IOException {
        systemService.checkConnection();
    }

    @Override
    public void createTable(String tableName, List<String> columnFamilies) throws IOException {
        systemService.createTable(tableName, columnFamilies);
    }

    @Override
    public void deleteData(String tableName, String rowKey) throws IOException {
        systemService.deleteData(tableName, rowKey);
    }

    @Override
    public void disableTable(String tableName) throws IOException {
        systemService.disableTable(tableName);
    }

    @Override
    public void dropTable(String tableName) throws IOException {
        systemService.dropTable(tableName);
    }

    @Override
    public void enableTable(String tableName) throws IOException {
        systemService.enableTable(tableName);
    }

    @Override
    public void insertData(String tableName, String rowKey, String columnFamily, String column, String cellValue)
        throws IOException {
        systemService.insertData(tableName, rowKey, columnFamily, column, cellValue);
    }

    @Override
    public Map<byte[], Map<byte[], Map<byte[], byte[]>>> scan(
        String tableName,
        Map<byte[], List<byte[]>> columns,
        byte[] rowKeyLowerBound,
        byte[] rowKeyUpperBound,
        int limit
    ) throws IOException {
        return systemService.scan(tableName, columns, rowKeyLowerBound, rowKeyUpperBound, limit);
    }
}
