package it.water.connectors.hbase.service.rest;

import it.water.connectors.hbase.api.HBaseConnectorApi;
import it.water.connectors.hbase.api.rest.HBaseConnectorRestApi;
import it.water.connectors.hbase.model.HBaseConnector;
import it.water.core.api.service.BaseEntityApi;
import it.water.core.api.service.rest.FrameworkRestController;
import it.water.core.interceptors.annotations.Inject;
import it.water.service.rest.persistence.BaseEntityRestApi;
import lombok.Setter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.util.Arrays;
import java.util.List;

/**
 * @Generated by Water Generator
 * Rest API class for HBaseConnector entity.
 */
@FrameworkRestController(referredRestApi = HBaseConnectorRestApi.class)
public class HBaseConnectorRestControllerImpl extends BaseEntityRestApi<HBaseConnector> implements HBaseConnectorRestApi {

    private static final Logger LOG = LoggerFactory.getLogger(HBaseConnectorRestControllerImpl.class);

    @Inject
    @Setter
    private HBaseConnectorApi hbaseConnectorApi;

    @Override
    protected BaseEntityApi<HBaseConnector> getEntityService() {
        return hbaseConnectorApi;
    }

    @Override
    public String checkConnection(long id) throws IOException {
        LOG.debug("Invoking /hbaseconnectors/{}/status", id);
        HBaseConnector connector = hbaseConnectorApi.find(id);
        if (connector == null) {
            return "Connector not found";
        }
        try {
            hbaseConnectorApi.checkConnection();
            return "HBase connection OK";
        } catch (IOException e) {
            return "HBase connection failed: " + e.getMessage();
        }
    }

    @Override
    public void createTable(long connectorId, String tableName, String columnFamilies) throws IOException {
        LOG.debug("Invoking /hbaseconnectors/{}/tables - Creating table {}", connectorId, tableName);
        requireConnector(connectorId);
        List<String> families = Arrays.asList(columnFamilies.split(","));
        hbaseConnectorApi.createTable(tableName, families);
    }

    @Override
    public void insertData(long connectorId, String tableName, String rowKey, String columnFamily, String column, String cellValue)
        throws IOException {
        LOG.debug("Invoking /hbaseconnectors/{}/data - Inserting into table {}", connectorId, tableName);
        requireConnector(connectorId);
        hbaseConnectorApi.insertData(tableName, rowKey, columnFamily, column, cellValue);
    }

    @Override
    public void deleteData(long connectorId, String tableName, String rowKey) throws IOException {
        LOG.debug("Invoking /hbaseconnectors/{}/data - Deleting from table {}", connectorId, tableName);
        requireConnector(connectorId);
        hbaseConnectorApi.deleteData(tableName, rowKey);
    }

    @Override
    public void enableTable(long connectorId, String tableName) throws IOException {
        LOG.debug("Invoking /hbaseconnectors/{}/tables - Enabling table {}", connectorId, tableName);
        requireConnector(connectorId);
        hbaseConnectorApi.enableTable(tableName);
    }

    @Override
    public void disableTable(long connectorId, String tableName) throws IOException {
        LOG.debug("Invoking /hbaseconnectors/{}/tables/disable - Disabling table {}", connectorId, tableName);
        requireConnector(connectorId);
        hbaseConnectorApi.disableTable(tableName);
    }

    @Override
    public void dropTable(long connectorId, String tableName) throws IOException {
        LOG.debug("Invoking /hbaseconnectors/{}/tables/drop - Dropping table {}", connectorId, tableName);
        requireConnector(connectorId);
        hbaseConnectorApi.dropTable(tableName);
    }

    private void requireConnector(long connectorId) throws IOException {
        HBaseConnector connector = hbaseConnectorApi.find(connectorId);
        if (connector == null) {
            throw new IOException("Connector not found");
        }
    }
}
