package it.water.connectors.hbase.service.options;

import it.water.connectors.hbase.api.options.HBaseConnectorOptions;
import it.water.core.api.bundle.ApplicationProperties;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import lombok.Setter;

/**
 * @Generated by Water Generator
 * Configuration options implementation for HBaseConnector.
 */
@FrameworkComponent
public class HBaseConnectorOptionsImpl implements HBaseConnectorOptions {

    @Inject
    @Setter
    private ApplicationProperties applicationProperties;

    private static final String PROP_MASTER_HOSTNAME = "hbaseconnector.master.hostname";
    private static final String PROP_MASTER_PORT = "hbaseconnector.master.port";
    private static final String PROP_ZOOKEEPER_QUORUM = "hbaseconnector.zookeeper.quorum";
    private static final String PROP_ROOTDIR = "hbaseconnector.rootdir";
    private static final String PROP_CLUSTER_DISTRIBUTED = "hbaseconnector.cluster.distributed";
    private static final String PROP_MASTER_INFO_PORT = "hbaseconnector.master.info.port";
    private static final String PROP_REGIONSERVER_PORT = "hbaseconnector.regionserver.port";
    private static final String PROP_REGIONSERVER_INFO_PORT = "hbaseconnector.regionserver.info.port";
    private static final String PROP_CORE_POOL_SIZE = "hbaseconnector.thread.corepool.size";
    private static final String PROP_MAXIMUM_POOL_SIZE = "hbaseconnector.thread.maximum.size";
    private static final String PROP_KEEP_ALIVE_TIME = "hbaseconnector.thread.keepalive.time";
    private static final String PROP_AWAIT_TERMINATION = "hbaseconnector.thread.await.termination";
    private static final String PROP_MAX_SCAN_PAGE_SIZE = "hbaseconnector.scan.max.page.size";

    @Override
    public String getMasterHostname() {
        return applicationProperties.getPropertyOrDefault(PROP_MASTER_HOSTNAME, "localhost");
    }

    @Override
    public int getMasterPort() {
        return Integer.parseInt(applicationProperties.getPropertyOrDefault(PROP_MASTER_PORT, "16000"));
    }

    @Override
    public String getZookeeperQuorum() {
        return applicationProperties.getPropertyOrDefault(PROP_ZOOKEEPER_QUORUM, "localhost");
    }

    @Override
    public String getRootdir() {
        return applicationProperties.getPropertyOrDefault(PROP_ROOTDIR, "hdfs://localhost:8020/hbase");
    }

    @Override
    public boolean getClusterDistributed() {
        return Boolean.parseBoolean(applicationProperties.getPropertyOrDefault(PROP_CLUSTER_DISTRIBUTED, "false"));
    }

    @Override
    public int getMasterInfoPort() {
        return Integer.parseInt(applicationProperties.getPropertyOrDefault(PROP_MASTER_INFO_PORT, "16010"));
    }

    @Override
    public int getRegionserverPort() {
        return Integer.parseInt(applicationProperties.getPropertyOrDefault(PROP_REGIONSERVER_PORT, "16020"));
    }

    @Override
    public int getRegionserverInfoPort() {
        return Integer.parseInt(applicationProperties.getPropertyOrDefault(PROP_REGIONSERVER_INFO_PORT, "16030"));
    }

    @Override
    public int getCorePoolSize() {
        return Integer.parseInt(applicationProperties.getPropertyOrDefault(PROP_CORE_POOL_SIZE, "10"));
    }

    @Override
    public int getMaximumPoolSize() {
        return Integer.parseInt(applicationProperties.getPropertyOrDefault(PROP_MAXIMUM_POOL_SIZE, "20"));
    }

    @Override
    public long getKeepAliveTime() {
        return Long.parseLong(applicationProperties.getPropertyOrDefault(PROP_KEEP_ALIVE_TIME, "0"));
    }

    @Override
    public long getAwaitTermination() {
        return Long.parseLong(applicationProperties.getPropertyOrDefault(PROP_AWAIT_TERMINATION, "1000"));
    }

    @Override
    public int getMaxScanPageSize() {
        return Integer.parseInt(applicationProperties.getPropertyOrDefault(PROP_MAX_SCAN_PAGE_SIZE, "2147483647"));
    }
}
