package it.water.connectors.hbase.api.options;

import it.water.core.api.service.Service;

/**
 * @Generated by Water Generator
 * Configuration options for HBaseConnector.
 */
public interface HBaseConnectorOptions extends Service {

    String getMasterHostname();

    int getMasterPort();

    String getZookeeperQuorum();

    String getRootdir();

    boolean getClusterDistributed();

    int getMasterInfoPort();

    int getRegionserverPort();

    int getRegionserverInfoPort();

    int getCorePoolSize();

    int getMaximumPoolSize();

    long getKeepAliveTime();

    long getAwaitTermination();

    int getMaxScanPageSize();
}
