package it.water.connectors.hbase.api.rest;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import it.water.core.api.service.rest.FrameworkRestApi;
import it.water.core.api.service.rest.RestApi;
import it.water.service.rest.api.security.LoggedIn;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.POST;
import javax.ws.rs.Produces;
import javax.ws.rs.PUT;
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import java.io.IOException;

/**
 * @Generated by Water Generator
 * Rest API for HBaseConnector custom HBase operations.
 */
@Path("/hbaseconnectors")
@Api(produces = MediaType.APPLICATION_JSON, tags = "HBaseConnector API")
@FrameworkRestApi
public interface HBaseConnectorRestApi extends RestApi {

    @LoggedIn
    @Path("/checkConnection")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @ApiOperation(
        value = "/hbaseconnectors/checkConnection",
        notes = "Check HBase client connection",
        httpMethod = "GET",
        produces = MediaType.APPLICATION_JSON,
        authorizations = @Authorization("jwt-auth")
    )
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 403, message = "Not authorized"),
        @ApiResponse(code = 500, message = "Connection failed")
    })
    String checkConnection() throws IOException;

    @GET
    @Path("/module/status")
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(
        value = "/hbaseconnectors/module/status",
        notes = "Simple service for checking module status",
        httpMethod = "GET",
        produces = MediaType.APPLICATION_JSON
    )
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 500, message = "Internal server error")
    })
    Response checkModuleWorking();

    @LoggedIn
    @Path("/tables")
    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @ApiOperation(
        value = "/hbaseconnectors/tables",
        notes = "Service for creating new table",
        httpMethod = "POST",
        produces = MediaType.APPLICATION_JSON,
        authorizations = @Authorization("jwt-auth")
    )
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 403, message = "Not authorized"),
        @ApiResponse(code = 422, message = "Not validated"),
        @ApiResponse(code = 500, message = "Internal error")
    })
    void createTable(
        @ApiParam(value = "Table name", required = true) @QueryParam("tableName") String tableName,
        @ApiParam(value = "Column families (comma-separated)", required = true) @QueryParam("columnFamilies") String columnFamilies
    ) throws IOException;

    @LoggedIn
    @Path("/tables")
    @PUT
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @ApiOperation(
        value = "/hbaseconnectors/tables",
        notes = "Service for insert data",
        httpMethod = "PUT",
        produces = MediaType.APPLICATION_JSON,
        authorizations = @Authorization("jwt-auth")
    )
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 403, message = "Not authorized"),
        @ApiResponse(code = 422, message = "Not validated"),
        @ApiResponse(code = 500, message = "Internal error")
    })
    void insertData(
        @ApiParam(value = "Table name", required = true) @QueryParam("tableName") String tableName,
        @ApiParam(value = "Row key", required = true) @QueryParam("rowKey") String rowKey,
        @ApiParam(value = "Column family", required = true) @QueryParam("columnFamily") String columnFamily,
        @ApiParam(value = "Column", required = true) @QueryParam("column") String column,
        @ApiParam(value = "Cell value", required = true) @QueryParam("cellValue") String cellValue
    ) throws IOException;

    @LoggedIn
    @Path("/tables/rows")
    @DELETE
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @ApiOperation(
        value = "/hbaseconnectors/tables/rows",
        notes = "Service for delete data",
        httpMethod = "DELETE",
        produces = MediaType.APPLICATION_JSON,
        authorizations = @Authorization("jwt-auth")
    )
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 403, message = "Not authorized"),
        @ApiResponse(code = 422, message = "Not validated"),
        @ApiResponse(code = 500, message = "Internal error")
    })
    void deleteData(
        @ApiParam(value = "Table name", required = true) @QueryParam("tableName") String tableName,
        @ApiParam(value = "Row key", required = true) @QueryParam("rowKey") String rowKey
    ) throws IOException;

    @LoggedIn
    @Path("/tables/{tableName}/enable")
    @PUT
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @ApiOperation(
        value = "/hbaseconnectors/tables/{tableName}/enable",
        notes = "Enable HBase table",
        httpMethod = "PUT",
        produces = MediaType.APPLICATION_JSON,
        authorizations = @Authorization("jwt-auth")
    )
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 403, message = "Not authorized"),
        @ApiResponse(code = 422, message = "Not validated"),
        @ApiResponse(code = 500, message = "Internal error")
    })
    void enableTable(@ApiParam(value = "Table name", required = true) @PathParam("tableName") String tableName)
        throws IOException;

    @LoggedIn
    @Path("/tables/{tableName}/disable")
    @PUT
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @ApiOperation(
        value = "/hbaseconnectors/tables/{tableName}/disable",
        notes = "Disable HBase table",
        httpMethod = "PUT",
        produces = MediaType.APPLICATION_JSON,
        authorizations = @Authorization("jwt-auth")
    )
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 403, message = "Not authorized"),
        @ApiResponse(code = 422, message = "Not validated"),
        @ApiResponse(code = 500, message = "Internal error")
    })
    void disableTable(@ApiParam(value = "Table name", required = true) @PathParam("tableName") String tableName)
        throws IOException;

    @LoggedIn
    @Path("/tables/{tableName}")
    @DELETE
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @ApiOperation(
        value = "/hbaseconnectors/tables/{tableName}",
        notes = "Drop HBase table",
        httpMethod = "DELETE",
        produces = MediaType.APPLICATION_JSON,
        authorizations = @Authorization("jwt-auth")
    )
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 403, message = "Not authorized"),
        @ApiResponse(code = 404, message = "Entity not found"),
        @ApiResponse(code = 500, message = "Internal error")
    })
    void dropTable(@ApiParam(value = "Table name", required = true) @PathParam("tableName") String tableName)
        throws IOException;
}
