package it.water.connectors.hbase.api.rest;

import com.fasterxml.jackson.annotation.JsonView;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import it.water.connectors.hbase.model.HBaseConnector;
import it.water.core.api.model.PaginableResult;
import it.water.core.api.service.rest.FrameworkRestApi;
import it.water.core.api.service.rest.RestApi;
import it.water.core.api.service.rest.WaterJsonView;
import it.water.service.rest.api.security.LoggedIn;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.MediaType;
import java.io.IOException;

/**
 * @Generated by Water Generator
 * Rest API for HBaseConnector CRUD and custom HBase operations.
 */
@Path("/hbaseconnectors")
@Api(produces = MediaType.APPLICATION_JSON, tags = "HBaseConnector API")
@FrameworkRestApi
public interface HBaseConnectorRestApi extends RestApi {

    @LoggedIn
    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @JsonView(WaterJsonView.Public.class)
    @ApiOperation(value = "/", notes = "HBaseConnector Save API", httpMethod = "POST", produces = MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 401, message = "Not authorized"),
        @ApiResponse(code = 409, message = "Validation Failed"),
        @ApiResponse(code = 422, message = "Duplicated Entity"),
        @ApiResponse(code = 500, message = "Internal server error")
    })
    HBaseConnector save(HBaseConnector entity);

    @LoggedIn
    @PUT
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @JsonView(WaterJsonView.Public.class)
    @ApiOperation(value = "/", notes = "HBaseConnector Update API", httpMethod = "PUT", produces = MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 401, message = "Not authorized"),
        @ApiResponse(code = 409, message = "Validation Failed"),
        @ApiResponse(code = 422, message = "Duplicated Entity"),
        @ApiResponse(code = 500, message = "Internal server error")
    })
    HBaseConnector update(HBaseConnector entity);

    @LoggedIn
    @Path("/{id}")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @JsonView(WaterJsonView.Public.class)
    @ApiOperation(value = "/{id}", notes = "HBaseConnector Find API", httpMethod = "GET", produces = MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 401, message = "Not authorized"),
        @ApiResponse(code = 409, message = "Validation Failed"),
        @ApiResponse(code = 422, message = "Duplicated Entity"),
        @ApiResponse(code = 500, message = "Internal server error")
    })
    HBaseConnector find(@PathParam("id") long id);

    @LoggedIn
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @JsonView(WaterJsonView.Public.class)
    @ApiOperation(value = "/", notes = "HBaseConnector Find All API", httpMethod = "GET", produces = MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 401, message = "Not authorized"),
        @ApiResponse(code = 409, message = "Validation Failed"),
        @ApiResponse(code = 422, message = "Duplicated Entity"),
        @ApiResponse(code = 500, message = "Internal server error")
    })
    PaginableResult<HBaseConnector> findAll();

    @LoggedIn
    @Path("/{id}")
    @DELETE
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @JsonView(WaterJsonView.Public.class)
    @ApiOperation(value = "/{id}", notes = "HBaseConnector Delete API", httpMethod = "DELETE", produces = MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful operation"),
        @ApiResponse(code = 401, message = "Not authorized"),
        @ApiResponse(code = 409, message = "Validation Failed"),
        @ApiResponse(code = 422, message = "Duplicated Entity"),
        @ApiResponse(code = 500, message = "Internal server error")
    })
    void remove(@PathParam("id") long id);

    @LoggedIn
    @Path("/{id}/status")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "/{id}/status", notes = "Check HBase connection status", httpMethod = "GET", produces = MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Connection OK"),
        @ApiResponse(code = 404, message = "Connector not found"),
        @ApiResponse(code = 500, message = "Connection failed")
    })
    @JsonView(WaterJsonView.Extended.class)
    String checkConnection(@PathParam("id") long id) throws IOException;

    @LoggedIn
    @Path("/{id}/tables")
    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "/{id}/tables", notes = "Create HBase table", httpMethod = "POST", produces = MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Table created"),
        @ApiResponse(code = 404, message = "Connector not found"),
        @ApiResponse(code = 500, message = "Internal error")
    })
    void createTable(
        @PathParam("id") long connectorId,
        @ApiParam(value = "Table name", required = true) @QueryParam("tableName") String tableName,
        @ApiParam(value = "Column families (comma-separated)", required = true) @QueryParam("columnFamilies") String columnFamilies
    ) throws IOException;

    @LoggedIn
    @Path("/{id}/data")
    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "/{id}/data", notes = "Insert data in HBase", httpMethod = "POST", produces = MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Data inserted"),
        @ApiResponse(code = 404, message = "Connector not found"),
        @ApiResponse(code = 500, message = "Internal error")
    })
    void insertData(
        @PathParam("id") long connectorId,
        @ApiParam(value = "Table name", required = true) @QueryParam("tableName") String tableName,
        @ApiParam(value = "Row key", required = true) @QueryParam("rowKey") String rowKey,
        @ApiParam(value = "Column family", required = true) @QueryParam("columnFamily") String columnFamily,
        @ApiParam(value = "Column", required = true) @QueryParam("column") String column,
        @ApiParam(value = "Cell value", required = true) @QueryParam("cellValue") String cellValue
    ) throws IOException;

    @LoggedIn
    @Path("/{id}/data")
    @DELETE
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "/{id}/data", notes = "Delete data from HBase", httpMethod = "DELETE", produces = MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Data deleted"),
        @ApiResponse(code = 404, message = "Connector not found"),
        @ApiResponse(code = 500, message = "Internal error")
    })
    void deleteData(
        @PathParam("id") long connectorId,
        @ApiParam(value = "Table name", required = true) @QueryParam("tableName") String tableName,
        @ApiParam(value = "Row key", required = true) @QueryParam("rowKey") String rowKey
    ) throws IOException;

    @LoggedIn
    @Path("/{id}/tables")
    @PUT
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "/{id}/tables", notes = "Enable HBase table", httpMethod = "PUT", produces = MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Table enabled"),
        @ApiResponse(code = 404, message = "Connector not found"),
        @ApiResponse(code = 500, message = "Internal error")
    })
    void enableTable(
        @PathParam("id") long connectorId,
        @ApiParam(value = "Table name", required = true) @QueryParam("tableName") String tableName
    ) throws IOException;

    @LoggedIn
    @Path("/{id}/tables/disable")
    @PUT
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "/{id}/tables/disable", notes = "Disable HBase table", httpMethod = "PUT", produces = MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Table disabled"),
        @ApiResponse(code = 404, message = "Connector not found"),
        @ApiResponse(code = 500, message = "Internal error")
    })
    void disableTable(
        @PathParam("id") long connectorId,
        @ApiParam(value = "Table name", required = true) @QueryParam("tableName") String tableName
    ) throws IOException;

    @LoggedIn
    @Path("/{id}/tables/drop")
    @DELETE
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "/{id}/tables/drop", notes = "Drop HBase table", httpMethod = "DELETE", produces = MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Table dropped"),
        @ApiResponse(code = 404, message = "Connector not found"),
        @ApiResponse(code = 500, message = "Internal error")
    })
    void dropTable(
        @PathParam("id") long connectorId,
        @ApiParam(value = "Table name", required = true) @QueryParam("tableName") String tableName
    ) throws IOException;
}
