package it.water.connectors.hbase.repository;

import it.water.connectors.hbase.api.HBaseConnectorRepository;
import it.water.connectors.hbase.model.HBaseConnector;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.repository.jpa.WaterJpaRepositoryImpl;

/**
 * @Generated by Water Generator
 * Repository class for HBaseConnector entity.
 */
@FrameworkComponent
public class HBaseConnectorRepositoryImpl extends WaterJpaRepositoryImpl<HBaseConnector> implements HBaseConnectorRepository {

    private static final String HBASE_CONNECTOR_PERSISTENCE_UNIT = "water-default-persistence-unit";

    public HBaseConnectorRepositoryImpl() {
        super(HBaseConnector.class, HBASE_CONNECTOR_PERSISTENCE_UNIT);
    }
}
